#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DragGesture.Resource", IsApplication=true)]

namespace DragGesture
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_content_left = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background_content_right = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background_degraded2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background_degraded3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int background_item_permission = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_admin = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_calender = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_map = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_settings = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_user = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int monoandroidsplash = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int Admin_List = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int DraggableViewBtn = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int DragnDropBtn = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int User_List = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int ViewIcon = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int ViewTxt = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int imageView1 = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int imgPicture4 = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int textView2 = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int textView3 = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DragDropControlCell = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DragDropMainLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
